// GENERATED PLACEHOLDER — replace this whole file.
//
// This file is normally generated by running:
//   flutterfire configure
// from the project root, once you've created a Firebase project in the
// console and linked it. That command writes real API keys and app IDs
// for each platform (Android/iOS/web) into this file.
//
// Until that's done, `DefaultFirebaseOptions.currentPlatform` intentionally
// throws below, and `FirebaseService.initialize()` catches that and falls
// back to `MockRecipeRepository` so the app keeps working with sample data.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'No Firebase options configured yet. Run `flutterfire configure`.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      default:
        throw UnsupportedError(
          'No Firebase options configured yet. Run `flutterfire configure`.',
        );
    }
  }
}
